name: Publish VS Code Extension

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install --include=dev && npm list --depth=0

      # This isn't really needed now, but if the repo
      # changes to have release dependencies it will be in the future
      - name: Run Audit Fix
        run: npm audit fix --omit=dev

      # Even though this is technically a release, since it it the only workflow
      # that will be run, this is still a good practice.
      - name: Run lint
        run: npm run lint

      - name: Package the VS Code extension
        run: npm run vscode:package

      - name: Publish the VS Code extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npm run vscode:publish
